name: Publish to NuGet

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Package version (e.g., 1.0.0)'
        required: true
        type: string

# Prevent concurrent publishes
concurrency:
  group: publish-nuget
  cancel-in-progress: false

permissions:
  id-token: write  # Required for OIDC authentication with NuGet.org
  contents: read
  attestations: write  # For package provenance

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://www.nuget.org/packages/HeroSD-JWT

    steps:
      - name: Determine version and tag
        id: version
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            TAG="${{ github.event.release.tag_name }}"
            VERSION="${TAG#v}"  # Remove 'v' prefix if present
          else
            VERSION="${{ inputs.version }}"
            TAG="v$VERSION"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "TAG=$TAG" >> $GITHUB_OUTPUT
          echo "Publishing version: $VERSION (tag: $TAG)"

      - name: Validate version format
        run: |
          VERSION="${{ steps.version.outputs.VERSION }}"
          if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+)?$ ]]; then
            echo "Error: Invalid version format: $VERSION"
            echo "Expected format: X.Y.Z or X.Y.Z-prerelease"
            exit 1
          fi
          echo "Version format validated: $VERSION"

      - name: Download packages from release
        run: |
          echo "Downloading packages from release ${{ steps.version.outputs.TAG }}..."

          # Create packages directory
          mkdir -p ./packages

          # Download all .nupkg and .snupkg files from the release
          gh release download ${{ steps.version.outputs.TAG }} \
            --pattern '*.nupkg' \
            --pattern '*.snupkg' \
            --dir ./packages

          echo "Downloaded packages:"
          ls -lh ./packages/
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Validate package contents
        run: |
          echo "Package contents:"
          for pkg in ./packages/*.nupkg; do
            if [ -f "$pkg" ]; then
              echo "=== $pkg ==="
              unzip -l "$pkg" || true
            fi
          done

      - name: Generate package provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: './packages/*.nupkg'

      - name: NuGet login (OIDC → temporary API key)
        uses: NuGet/login@v1
        id: nuget-login
        with:
          user: ${{ secrets.NUGET_USERNAME }}
          # Uses GitHub Actions OIDC token to get a temporary (1-hour) NuGet API key
          # No long-lived API keys needed!

      - name: Publish to NuGet.org using Trusted Publishing
        run: |
          dotnet nuget push "./packages/*.nupkg" \
            --source https://api.nuget.org/v3/index.json \
            --api-key ${{ steps.nuget-login.outputs.NUGET_API_KEY }} \
            --skip-duplicate

      - name: Upload package artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages-v${{ steps.version.outputs.VERSION }}
          path: |
            ./packages/*.nupkg
            ./packages/*.snupkg
          retention-days: 90

      - name: Create release summary
        run: |
          echo "## NuGet Package Published" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Version**: ${{ steps.version.outputs.VERSION }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Package**: https://www.nuget.org/packages/HeroSD-JWT/${{ steps.version.outputs.VERSION }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Published**: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Installation" >> $GITHUB_STEP_SUMMARY
          echo '```bash' >> $GITHUB_STEP_SUMMARY
          echo "dotnet add package HeroSD-JWT --version ${{ steps.version.outputs.VERSION }}" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
